export const GET_SUPERADMIN_PENDING = 'GET_SUPERADMIN_PENDING';
export const GET_SUPERADMIN_SUCCESS = 'GET_SUPERADMIN_SUCCESS';
export const GET_SUPERADMIN_ERROR = 'GET_SUPERADMIN_ERROR';
export const ADD_SUPERADMIN_SUCCESS = 'ADD_SUPERADMIN_SUCCESS';
export const EDIT_SUPERADMIN_SUCCESS = 'EDIT_SUPERADMIN_SUCCESS';
export const DELETE_SUPERADMIN_PENDING = 'DELETE_SUPERADMIN_PENDING';
export const DELETE_SUPERADMIN_SUCCESS = 'DELETE_SUPERADMIN_SUCCESS';
export const DELETE_SUPERADMIN_ERROR = 'DELETE_SUPERADMIN_ERROR';
