export const GET_SUPERADMIN_PENDING = 'GET_SUPERADMIN_PENDING';
export const GET_SUPERADMIN_SUCCESS = 'GET_SUPERADMIN_SUCCESS';
export const GET_SUPERADMIN_ERROR = 'GET_SUPERADMIN_ERROR';
export const POST_SUPERADMIN_PENDING = 'POST_SUPERADMIN_PENDING';
export const POST_SUPERADMIN_SUCCESS = 'POST_SUPERADMIN_SUCCESS';
export const POST_SUPERADMIN_ERROR = 'POST_SUPERADMIN_ERROR';
