export const ADD_TRAINER_PENDING = 'ADD_TRAINER_PENDING';
export const ADD_TRAINER = 'ADD_TRAINER';
export const ADD_TRAINER_ERROR = 'ADD_TRAINER_ERROR';

export const UPDATE_TRAINER_PENDING = 'UPDATE_TRAINER_PENDING';
export const UPDATE_TRAINER = 'UPDATE_TRAINER';
export const UPDATE_TRAINER_ERROR = 'UPDATE_TRAINER_ERROR';
