export const GET_TRAINERS_PENDING = 'GET_TRAINERS_PENDING';
export const GET_TRAINERS_SUCCESS = 'GET_TRAINERS_SUCCESS';
export const GET_TRAINERS_FAILURE = 'GET_TRAINERS_FAILURE';
export const DELETE_TRAINER_PENDING = 'DELETE_TRAINER_PENDING';
export const DELETE_TRAINER_SUCCESS = 'DELETE_TRAINER_SUCCESS';
export const DELETE_TRAINER_FAILURE = 'DELETE_TRAINER_FAILURE';
