export const GET_TRAINERS_REQUEST = 'GET_TRAINERS_REQUEST';
export const GET_TRAINERS_SUCCESS = 'GET_TRAINERS_SUCCESS';
export const GET_TRAINERS_FAILURE = 'GET_TRAINERS_FAILURE';
export const DELETE_TRAINER_REQUEST = 'DELETE_TRAINER_REQUEST';
export const DELETE_TRAINER_SUCCESS = 'DELETE_TRAINER_SUCCESS';
export const DELETE_TRAINER_FAILURE = 'DELETE_TRAINER_FAILURE';
